# Generated by Django 2.1.3 on 2018-12-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20181212_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body_material',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='bonnet_bolting_material',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='end_connections',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='fire_safe',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='leakage_class',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='nace_requirement',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='rating',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='seat_material',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='stem_material',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='trim_material',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='trim_size',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AddField(
            model_name='post',
            name='trim_type',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='body_size',
            field=models.CharField(default='empty', max_length=100),
        ),
        migrations.AlterField(
            model_name='post',
            name='valve_type',
            field=models.CharField(default='empty', max_length=100),
        ),
    ]
