# Generated by Django 2.1.3 on 2018-12-13 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20181213_0820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body_material',
            new_name='m_body_material',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='body_size',
            new_name='m_body_size',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='bonnet_bolting_material',
            new_name='m_bonnet_bolting_material',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='end_connections',
            new_name='m_end_connections',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='fire_safe',
            new_name='m_fire_safe',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='leakage_class',
            new_name='m_leakage_class',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='nace_requirement',
            new_name='m_nace_requirement',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='rating',
            new_name='m_rating',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='seat_material',
            new_name='m_seat_material',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='stem_material',
            new_name='m_stem_material',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='trim_material',
            new_name='m_trim_material',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='trim_size',
            new_name='m_trim_size',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='trim_type',
            new_name='m_trim_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='valve_type',
            new_name='m_valve_type',
        ),
    ]
